import fs from 'fs';
import yaml from 'yaml';

const translations = {
  en: [
    { id: "Afyon", name: "Opium", desc: "Addictions, deception, illusions, and toxic bonds." },
    { id: "Ağaç", name: "Tree", desc: "Rooting, health, growth, family lineage, and longevity." },
    { id: "Alyans", name: "Wedding Ring", desc: "Commitment, marriage, partnership, serious completion." },
    { id: "Anahtar", name: "Key", desc: "Solution and new beginnings. Secrets being revealed." },
    { id: "Ay", name: "Moon", desc: "Intuition, romance, melancholy, and changing moods." },
    { id: "Bahçeler", name: "Gardens", desc: "Socializing, environment, crowds, and your place in society." },
    { id: "Balık", name: "Fish", desc: "Symbolizes financial gain, abundance, and luck." },
    { id: "Baykuş", name: "Owl", desc: "Wisdom, news arriving at night, or a time to observe." },
    { id: "Bulutlar", name: "Clouds", desc: "Confusion, uncertainty, or temporary troubles." },
    { id: "Çapa", name: "Anchor", desc: "Trust, loyalty, attachment to a place or person, hope." },
    { id: "Çiçekler", name: "Flowers", desc: "Happiness, beauty, gifts, and pleasant surprises." },
    { id: "Dağ", name: "Mountain", desc: "Obstacles, difficult situations, delays, and tests." },
    { id: "Derviş", name: "Dervish", desc: "Wisdom, solitude, patience, and spiritual guidance." },
    { id: "Deve", name: "Camel", desc: "Patience in financial matters, stubbornness, or a long journey." },
    { id: "Ev", name: "House", desc: "Peace, security, family life, and the place of your roots." },
    { id: "Fareler", name: "Mice", desc: "Losses, inner gnawing worry, and stress." },
    { id: "Güneş", name: "Sun", desc: "Great luck, happiness, enlightenment, and success." },
    { id: "Haç", name: "Cross", desc: "A twist of fate, obligations, or painful but necessary experiences." },
    { id: "Kale", name: "Castle", desc: "Security, solid structure, being protected against external factors." },
    { id: "Kalp", name: "Heart", desc: "Great love, affection, compassion, and emotional happiness." },
    { id: "Kapı", name: "Door", desc: "Opportunities, newly opened paths, or a decision to be made." },
    { id: "Kitap", name: "Book", desc: "Secrets, education, a surprising truth to be learned." },
    { id: "Köpek", name: "Dog", desc: "Loyalty, an honest friendship, or reliable support." },
    { id: "KızÇocuğu", name: "Little Girl", desc: "Innocence, new beginnings, or a youthful energy." },
    { id: "Mektup", name: "Letter", desc: "News, an expected message, or important communication." },
    { id: "Mezar", name: "Grave", desc: "Endings, significant change, the closing of an era and the beginning of a new one." },
    { id: "NilNehri", name: "Nile River", desc: "Represents abundance, flow, and a long, fruitful process." },
    { id: "Samyeli", name: "Simoom", desc: "Unexpected events, sudden changes, or temporary winds." },
    { id: "Süpürge", name: "Broom", desc: "Cleansing, quarrels, the need to remove things from your life." },
    { id: "Tilki", name: "Fox", desc: "Cunning, an opportunism that requires caution." },
    { id: "Yatağan", name: "Yataghan", desc: "Sharp decisions, power, defense, or an approaching danger." },
    { id: "Yelkenli", name: "Sailboat", desc: "Journeys, going with the flow, or news arriving from afar." },
    { id: "Yol", name: "Path", desc: "Choices, separations, or a step taken towards a new life." },
    { id: "Yılan", name: "Snake", desc: "Betrayal, hidden hostility, jealousy, or sneakiness." },
    { id: "Yıldızlar", name: "Stars", desc: "Hope, inspiration, dreams coming true, spiritual guidance." }
  ],
  tr: [
    { id: "Afyon", name: "Afyon", desc: "Bağımlılıklar, göz boyama, illüzyonlar ve toksik bağlar." },
    { id: "Ağaç", name: "Ağaç", desc: "Köklenme, sağlık, büyüme, aile soyu ve uzun ömür." },
    { id: "Alyans", name: "Alyans", desc: "Bağlılık, evlilik, ortaklık, ciddi bir tamamlanma." },
    { id: "Anahtar", name: "Anahtar", desc: "Çözüm ve yeni başlangıçlar. Sırların açığa çıkması." },
    { id: "Ay", name: "Ay", desc: "Sezgiler, romantizm, melankoli ve değişken ruh halleri." },
    { id: "Bahçeler", name: "Bahçeler", desc: "Sosyalleşme, çevre, kalabalıklar ve toplum içindeki yeriniz." },
    { id: "Balık", name: "Balık", desc: "Maddi kazanç, bolluk ve şansın simgesidir." },
    { id: "Baykuş", name: "Baykuş", desc: "Bilgelik, gece gelen haberler veya etrafı gözlemleme zamanı." },
    { id: "Bulutlar", name: "Bulutlar", desc: "Kafa karışıklığı, belirsizlik veya geçici sıkıntılar." },
    { id: "Çapa", name: "Çapa", desc: "Güven, sadakat, bir yere veya kişiye bağlılık, umut." },
    { id: "Çiçekler", name: "Çiçekler", desc: "Mutluluk, güzellik, armağanlar ve hoş sürprizler." },
    { id: "Dağ", name: "Dağ", desc: "Engeller, aşılması zor durumlar, gecikmeler ve sınanmalar." },
    { id: "Derviş", name: "Derviş", desc: "Bilgelik, yalnızlık, sabır ve manevi rehberlik." },
    { id: "Deve", name: "Deve", desc: "Finansal konularda sabır, inatçılık veya uzun bir yolculuk." },
    { id: "Ev", name: "Ev", desc: "Huzur, güvenlik, aile yaşantısı ve köklerin olduğu yer." },
    { id: "Fareler", name: "Fareler", desc: "Kayıplar, içten içe kemiren endişe ve stres." },
    { id: "Güneş", name: "Güneş", desc: "Büyük şans, mutluluk, aydınlanma ve başarı." },
    { id: "Haç", name: "Haç", desc: "Kaderin bir cilvesi, zorunluluklar veya acı ama gerekli tecrübeler." },
    { id: "Kale", name: "Kale", desc: "Güvenlik, sağlam yapı, dış etkenlere karşı korunaklı olma." },
    { id: "Kalp", name: "Kalp", desc: "Büyük aşk, sevgi, şefkat ve duygusal mutluluk." },
    { id: "Kapı", name: "Kapı", desc: "Fırsatlar, açılan yeni yollar veya verilmesi gereken bir karar." },
    { id: "Kitap", name: "Kitap", desc: "Sırlar, eğitim, öğrenilmesi gereken şaşırtıcı bir gerçek." },
    { id: "Köpek", name: "Köpek", desc: "Sadakat, dürüst bir dostluk veya güvenilir destek." },
    { id: "KızÇocuğu", name: "Kız Çocuğu", desc: "Masumiyet, yeni başlangıçlar veya genç bir enerji." },
    { id: "Mektup", name: "Mektup", desc: "Haberler, beklenen bir mesaj veya önemli bir iletişim." },
    { id: "Mezar", name: "Mezar", desc: "Bitişler, büyük değişim, bir devrin kapanıp yenisinin başlaması." },
    { id: "NilNehri", name: "Nil Nehri", desc: "Bereketi, akışı, uzun ve verimli bir süreci temsil eder." },
    { id: "Samyeli", name: "Samyeli", desc: "Beklenmedik olaylar, ani değişimler veya geçici rüzgarlar." },
    { id: "Süpürge", name: "Süpürge", desc: "Temizlenme, kavga, hayatından bir şeyleri çıkarma gerekliliği." },
    { id: "Tilki", name: "Tilki", desc: "Kurnazlık, dikkatli olunması gereken bir fırsatçılık." },
    { id: "Yatağan", name: "Yatağan", desc: "Keskin kararlar, güç, savunma veya yaklaşan bir tehlike." },
    { id: "Yelkenli", name: "Yelkenli", desc: "Yolculuklar, akışta kalmak veya uzaktan gelecek bir haber." },
    { id: "Yol", name: "Yol", desc: "Seçimler, ayrılıklar ya da yeni bir hayata doğru atılan adım." },
    { id: "Yılan", name: "Yılan", desc: "İhanet, gizli düşmanlık, kıskançlık veya sinsilik." },
    { id: "Yıldızlar", name: "Yıldızlar", desc: "Umut, ilham, hayallerin gerçekleşmesi, ruhsal rehberlik." }
  ],
  es: [
    { id: "Afyon", name: "Opio", desc: "Adicciones, engaños, ilusiones y vínculos tóxicos." },
    { id: "Ağaç", name: "Árbol", desc: "Arraigo, salud, crecimiento, linaje familiar y longevidad." },
    { id: "Alyans", name: "Anillo de bodas", desc: "Compromiso, matrimonio, asociación, una finalización seria." },
    { id: "Anahtar", name: "Llave", desc: "Solución y nuevos comienzos. Secretos revelados." },
    { id: "Ay", name: "Luna", desc: "Intuición, romance, melancolía y cambios de humor." },
    { id: "Bahçeler", name: "Jardines", desc: "Socialización, entorno, multitudes y tu lugar en la sociedad." },
    { id: "Balık", name: "Peces", desc: "Simboliza beneficio económico, abundancia y suerte." },
    { id: "Baykuş", name: "Búho", desc: "Sabiduría, noticias durante la noche o un momento para observar." },
    { id: "Bulutlar", name: "Nubes", desc: "Confusión, incertidumbre o problemas temporales." },
    { id: "Çapa", name: "Ancla", desc: "Confianza, lealtad, apego a un lugar o persona, esperanza." },
    { id: "Çiçekler", name: "Flores", desc: "Felicidad, belleza, regalos y agradables sorpresas." },
    { id: "Dağ", name: "Montaña", desc: "Obstáculos, situaciones difíciles, retrasos y pruebas." },
    { id: "Derviş", name: "Derviche", desc: "Sabiduría, soledad, paciencia y guía espiritual." },
    { id: "Deve", name: "Camello", desc: "Paciencia en asuntos financieros, terquedad o un largo viaje." },
    { id: "Ev", name: "Casa", desc: "Paz, seguridad, vida familiar y el lugar de tus raíces." },
    { id: "Fareler", name: "Ratones", desc: "Pérdidas, preocupación que carcome por dentro y estrés." },
    { id: "Güneş", name: "Sol", desc: "Gran suerte, felicidad, iluminación y éxito." },
    { id: "Haç", name: "Cruz", desc: "Un giro del destino, obligaciones o experiencias dolorosas pero necesarias." },
    { id: "Kale", name: "Castillo", desc: "Seguridad, estructura sólida, estar protegido contra factores externos." },
    { id: "Kalp", name: "Corazón", desc: "Gran amor, afecto, compasión y felicidad emocional." },
    { id: "Kapı", name: "Puerta", desc: "Oportunidades, nuevos caminos abiertos o una decisión a tomar." },
    { id: "Kitap", name: "Libro", desc: "Secretos, educación, una verdad sorprendente que aprender." },
    { id: "Köpek", name: "Perro", desc: "Lealtad, una amistad honesta o apoyo confiable." },
    { id: "KızÇocuğu", name: "Niña", desc: "Inocencia, nuevos comienzos o una energía juvenil." },
    { id: "Mektup", name: "Carta", desc: "Noticias, un mensaje esperado o comunicación importante." },
    { id: "Mezar", name: "Tumba", desc: "Finales, un gran cambio, el cierre de una era y el comienzo de una nueva." },
    { id: "NilNehri", name: "Río Nilo", desc: "Representa la abundancia, el fluir y un proceso largo y fructífero." },
    { id: "Samyeli", name: "Viento cálido", desc: "Eventos inesperados, cambios repentinos o vientos pasajeros." },
    { id: "Süpürge", name: "Escoba", desc: "Limpieza, peleas, la necesidad de eliminar cosas de tu vida." },
    { id: "Tilki", name: "Zorro", desc: "Astucia, un oportunismo que requiere precaución." },
    { id: "Yatağan", name: "Alfanje", desc: "Decisiones tajantes, poder, defensa o un peligro inminente." },
    { id: "Yelkenli", name: "Velero", desc: "Viajes, dejarse llevar o noticias que llegan desde lejos." },
    { id: "Yol", name: "Camino", desc: "Elecciones, separaciones o un paso hacia una nueva vida." },
    { id: "Yılan", name: "Serpiente", desc: "Traición, hostilidad oculta, celos o astucia malintencionada." },
    { id: "Yıldızlar", name: "Estrellas", desc: "Esperanza, inspiración, sueños que se cumplen, guía espiritual." }
  ],
  fr: [
    { id: "Afyon", name: "Opium", desc: "Addictions, tromperie, illusions et liens toxiques." },
    { id: "Ağaç", name: "Arbre", desc: "Enracinement, santé, croissance, lignée familiale et longévité." },
    { id: "Alyans", name: "Alliance", desc: "Engagement, mariage, partenariat, un achèvement sérieux." },
    { id: "Anahtar", name: "Clé", desc: "Solution et nouveaux départs. Les secrets sont révélés." },
    { id: "Ay", name: "Lune", desc: "Intuition, romance, mélancolie et humeurs changeantes." },
    { id: "Bahçeler", name: "Jardins", desc: "Socialisation, environnement, foules et votre place dans la société." },
    { id: "Balık", name: "Poissons", desc: "Symbolise le gain financier, l'abondance et la chance." },
    { id: "Baykuş", name: "Hibou", desc: "Sagesse, nouvelles nocturnes ou le moment d'observer." },
    { id: "Bulutlar", name: "Nuages", desc: "Confusion, incertitude ou troubles temporaires." },
    { id: "Çapa", name: "Ancre", desc: "Confiance, loyauté, attachement à un lieu ou à une personne, espoir." },
    { id: "Çiçekler", name: "Fleurs", desc: "Bonheur, beauté, cadeaux et agréables surprises." },
    { id: "Dağ", name: "Montagne", desc: "Obstacles, situations difficiles, retards et épreuves." },
    { id: "Derviş", name: "Derviche", desc: "Sagesse, solitude, patience et conseils spirituels." },
    { id: "Deve", name: "Chameau", desc: "Patience en affaires financières, entêtement ou un long voyage." },
    { id: "Ev", name: "Maison", desc: "Paix, sécurité, vie de famille et la place de vos racines." },
    { id: "Fareler", name: "Souris", desc: "Pertes, inquiétudes intérieures rongeantes et stress." },
    { id: "Güneş", name: "Soleil", desc: "Grande chance, bonheur, illumination et succès." },
    { id: "Haç", name: "Croix", desc: "Un coup du sort, des obligations ou des expériences douloureuses mais nécessaires." },
    { id: "Kale", name: "Château", desc: "Sécurité, structure solide, être protégé des facteurs externes." },
    { id: "Kalp", name: "Cœur", desc: "Grand amour, affection, compassion et bonheur émotionnel." },
    { id: "Kapı", name: "Porte", desc: "Opportunités, nouveaux chemins ou une décision à prendre." },
    { id: "Kitap", name: "Livre", desc: "Secrets, éducation, une vérité surprenante à apprendre." },
    { id: "Köpek", name: "Chien", desc: "Loyauté, une amitié honnête ou un soutien fiable." },
    { id: "KızÇocuğu", name: "Petite fille", desc: "Innocence, nouveaux départs ou une énergie de jeunesse." },
    { id: "Mektup", name: "Lettre", desc: "Nouvelles, un message attendu ou une communication importante." },
    { id: "Mezar", name: "Tombe", desc: "Fins, changement majeur, la fin d'une époque et le début d'une autre." },
    { id: "NilNehri", name: "Nil", desc: "Représente l'abondance, le flux et un processus long et fructueux." },
    { id: "Samyeli", name: "Vent chaud", desc: "Événements inattendus, changements soudains ou vents temporaires." },
    { id: "Süpürge", name: "Balai", desc: "Nettoyage, querelles, la nécessité de retirer des choses de votre vie." },
    { id: "Tilki", name: "Renard", desc: "Ruse, un opportunisme qui requiert la prudence." },
    { id: "Yatağan", name: "Cimeterre", desc: "Décisions tranchantes, pouvoir, défense ou un danger qui approche." },
    { id: "Yelkenli", name: "Voilier", desc: "Voyages, se laisser porter ou des nouvelles venant de loin." },
    { id: "Yol", name: "Chemin", desc: "Choix, séparations ou un pas vers une nouvelle vie." },
    { id: "Yılan", name: "Serpent", desc: "Trahison, hostilité cachée, jalousie ou perfidie." },
    { id: "Yıldızlar", name: "Étoiles", desc: "Espoir, inspiration, rêves qui se réalisent, conseils spirituels." }
  ],
  zh: [
    { id: "Afyon", name: "鸦片", desc: "成瘾，欺骗，幻觉和有毒的联系。" },
    { id: "Ağaç", name: "树木", desc: "生根，健康，成长，家族血统和长寿。" },
    { id: "Alyans", name: "婚戒", desc: "承诺，婚姻，伙伴关系，一个严肃的完成。" },
    { id: "Anahtar", name: "钥匙", desc: "解决方案和新的开始。秘密被揭露。" },
    { id: "Ay", name: "月亮", desc: "直觉，浪漫，忧郁和改变的情绪。" },
    { id: "Bahçeler", name: "花园", desc: "社交，环境，人群和你在社会中的位置。" },
    { id: "Balık", name: "鱼", desc: "象征财务收益、丰富和好运。" },
    { id: "Baykuş", name: "猫头鹰", desc: "智慧、夜间消息或观察的时刻。" },
    { id: "Bulutlar", name: "云彩", desc: "混乱，不确定或暂时的麻烦。" },
    { id: "Çapa", name: "锚", desc: "信任、忠诚、对某个地方或某个人的依恋，希望。" },
    { id: "Çiçekler", name: "花", desc: "幸福、美丽、礼物和令人愉快的惊喜。" },
    { id: "Dağ", name: "山", desc: "障碍、困难的情况、延误和考验。" },
    { id: "Derviş", name: "苦行僧", desc: "智慧、孤独、耐心和精神指引。" },
    { id: "Deve", name: "骆驼", desc: "在财务问题上的耐心、固执或漫长的旅程。" },
    { id: "Ev", name: "房子", desc: "和平、安全、家庭生活和你扎根的地方。" },
    { id: "Fareler", name: "老鼠", desc: "损失、内心的忧郁和压力。" },
    { id: "Güneş", name: "太阳", desc: "好运、幸福、启蒙和成功。" },
    { id: "Haç", name: "十字架", desc: "命运的转折、义务或痛苦但必要的经历。" },
    { id: "Kale", name: "城堡", desc: "安全、坚固的结构、受到保护免受外部因素的影响。" },
    { id: "Kalp", name: "心", desc: "伟大的爱、感情、同情和感性的幸福。" },
    { id: "Kapı", name: "门", desc: "机遇、新开辟的道路或需要做出的决定。" },
    { id: "Kitap", name: "书", desc: "秘密、教育，一个令人惊讶的要被学习的真相。" },
    { id: "Köpek", name: "狗", desc: "忠诚、诚实的友谊或可靠的支持。" },
    { id: "KızÇocuğu", name: "小女孩", desc: "纯真、新的开始或年轻的活力。" },
    { id: "Mektup", name: "信", desc: "消息、预期中的信息或重要的交流。" },
    { id: "Mezar", name: "坟墓", desc: "结束、重大的变化、一个时代的结束和另一个时代的开始。" },
    { id: "NilNehri", name: "尼罗河", desc: "代表丰富、流动和漫长且富有成果的过程。" },
    { id: "Samyeli", name: "热风", desc: "意想不到的事件、突然的改变或暂时的风。" },
    { id: "Süpürge", name: "扫帚", desc: "清理、争吵，需要把一些事情从生活中清除。" },
    { id: "Tilki", name: "狐狸", desc: "狡猾、需要小心防范的机会主义者。" },
    { id: "Yatağan", name: "弯刀", desc: "果断的决定、力量、防御或迫近的危险。" },
    { id: "Yelkenli", name: "帆船", desc: "旅程、随波逐流或从远方传来的消息。" },
    { id: "Yol", name: "道路", desc: "选择、分离，或者迈向新生活的一步。" },
    { id: "Yılan", name: "蛇", desc: "背叛、隐藏的敌意、嫉妒或偷偷摸摸。" },
    { id: "Yıldızlar", name: "星辰", desc: "希望、灵感、梦想成真、精神指引。" }
  ],
  ko: [
    { id: "Afyon", name: "아편", desc: "중독, 속임수, 환상, 그리고 유해한 관계." },
    { id: "Ağaç", name: "나무", desc: "뿌리 내림, 건강, 성장, 가족의 가계 및 장수." },
    { id: "Alyans", name: "결혼 반지", desc: "헌신, 결혼, 파트너십, 진지한 완성." },
    { id: "Anahtar", name: "열쇠", desc: "해결책과 새로운 시작. 비밀이 드러남." },
    { id: "Ay", name: "달", desc: "직관, 로맨스, 우울함 및 변덕스러운 기분." },
    { id: "Bahçeler", name: "정원", desc: "사교, 환경, 군중 및 사회에서의 당신의 위치." },
    { id: "Balık", name: "물고기", desc: "재정적 이득, 풍요, 행운을 상징." },
    { id: "Baykuş", name: "올빼미", desc: "지혜, 밤에 오는 소식 또는 관찰할 시간." },
    { id: "Bulutlar", name: "구름", desc: "혼란, 불확실성 또는 일시적인 문제." },
    { id: "Çapa", name: "닻", desc: "신뢰, 충성도, 장소나 사람에 대한 애착, 희망." },
    { id: "Çiçekler", name: "꽃", desc: "행복, 아름다움, 선물 및 기분 좋은 놀라움." },
    { id: "Dağ", name: "산", desc: "장애물, 어려운 상황, 지연 및 시험." },
    { id: "Derviş", name: "수도승", desc: "지혜, 고독, 인내, 영적인 가이드." },
    { id: "Deve", name: "낙타", 기: "재정적 문제에서의 인내, 고집 또는 긴 여정." },
    { id: "Ev", name: "집", desc: "평화, 안정, 가족 생활, 뿌리가 있는 곳." },
    { id: "Fareler", name: "쥐", desc: "손실, 내부에서 갉아먹는 걱정과 스트레스." },
    { id: "Güneş", name: "태양", desc: "큰 행운, 행복, 깨달음 및 성공." },
    { id: "Haç", name: "십자가", desc: "운명의 장난, 의무, 또는 고통스럽지만 필요한 경험." },
    { id: "Kale", name: "성", desc: "안전, 견고한 구조, 외부 요인으로부터 보호됨." },
    { id: "Kalp", name: "심장", desc: "큰 사랑, 애정, 동정심 및 감정적인 행복." },
    { id: "Kapı", name: "문", desc: "기회, 새롭게 열린 길 또는 내려야 할 결정." },
    { id: "Kitap", name: "책", desc: "비밀, 교육, 알게 될 놀라운 진실." },
    { id: "Köpek", name: "개", desc: "충성, 정직한 우정 또는 믿을 수 있는 지원." },
    { id: "KızÇocuğu", name: "어린 소녀", desc: "순수함, 새로운 시작 또는 젊은 에너지." },
    { id: "Mektup", name: "편지", desc: "소식, 예상된 메시지 또는 중요한 커뮤니케이션." },
    { id: "Mezar", name: "무덤", desc: "결말, 큰 변화, 한 시대의 끝과 새로운 시대의 시작." },
    { id: "NilNehri", name: "나일강", desc: "풍요로움, 흐름 및 길고 결실이 있는 과정을 나타냄." },
    { id: "Samyeli", name: "따뜻한 바람", desc: "예기치 않은 사건, 갑작스러운 변화 또는 일시적인 바람." },
    { id: "Süpürge", name: "빗자루", desc: "정화, 말다툼, 삶에서 무언가를 제거할 필요성." },
    { id: "Tilki", name: "여우", desc: "교활함, 주의가 필요한 기회주의." },
    { id: "Yatağan", name: "언월도", desc: "날카로운 결정, 힘, 방어 또는 다가오는 위험." },
    { id: "Yelkenli", name: "범선", desc: "여행, 흐름에 맡기기 또는 멀리서 오는 소식." },
    { id: "Yol", name: "길", desc: "선택, 이별, 또는 새로운 삶을 향한 발걸음." },
    { id: "Yılan", name: "뱀", desc: "배신, 숨겨진 적대감, 질투 또는 교활함." },
    { id: "Yıldızlar", name: "별", desc: "희망, 영감, 이루어지는 꿈, 영적인 인도." }
  ]
};

for (const lang of Object.keys(translations)) {
  const fileContent = fs.readFileSync(`src/locales/${lang}.yaml`, 'utf8');
  let data;
  try {
    data = yaml.parse(fileContent);
  } catch (e) {
    console.error(`Error parsing ${lang}.yaml`);
    continue;
  }
  
  data.cards = {};
  for(const card of translations[lang]) {
    data.cards[card.id] = { name: card.name, desc: card.desc };
  }
  
  fs.writeFileSync(`src/locales/${lang}.yaml`, yaml.stringify(data));
  console.log(`Updated ${lang}.yaml`);
}
